Prime Number Solver: PHP HTML Functions
PHP HTML Functions
Functions
PrintDebug ($str)
Used for printing debug statements.
PrintHtmlFooter ()
Prints the standard HTML footer at bottom of each page.
PrintHtmlHeader ($title, $jsFiles)
Prints the standard HTML header at top of each page.
SetStickeyValue ($requestKey, $defaultValue)
Sets the value of the widget to the previous submission value.
WhereAmI ($function, $fileName, $line)
Used for generating a simple code traceback.
Function Documentation
PrintDebug ($ str)
Used for printing debug statements.
Prints the passed string if the key $_REQUEST['debug'] or $_REQUEST['DEBUG'] is set. Can be turned on by adding a hidden input control into a form. For example:
 <input type="hidden" name="debug" />
Author:
Fred R. McClurg
Date:
February 6, 2010
Parameters:
$str String to be printed
Definition at line 122 of file htmlFunctions.php.
Referenced by WhereAmI().
PrintHtmlFooter ()
Prints the standard HTML footer at bottom of each page.
Author:
Fred R. McClurg
Date:
February 6, 2010
See also:
PrintHtmlHeader
Definition at line 63 of file htmlFunctions.php.
References WhereAmI().
PrintHtmlHeader ($ title, $ jsFiles)
Prints the standard HTML header at top of each page.
Author:
Fred R. McClurg
Date:
February 6, 2010
See also:
PrintHtmlFooter
Parameters:
$title Used in the HTML page title and the <H1> title
$jsFiles Array containing JavaScript files
Definition at line 20 of file htmlFunctions.php.
References $jsFiles, $title, and WhereAmI().
SetStickeyValue ($ requestKey, $ defaultValue)
Sets the value of the widget to the previous submission value.
Author:
Fred R. McClurg
Date:
February 6, 2010
Parameters:
$requestKey Value user entered from previous submission. Example:
 <?= $_REQUEST['valueText'] ?>
$defaultValue Fallback value if previous submission value is undefined.
Return values:
$returnedValue Returns previously submitted value or the default.
Definition at line 93 of file htmlFunctions.php.
WhereAmI ($ function, $ fileName, $ line)
Used for generating a simple code traceback.
Example call usage:
 WhereAmI( __FUNCTION__, __FILE__, __LINE__ );
Author:
Fred R. McClurg
Date:
February 6, 2010
Parameters:
$function Function name of calling function (used with "__FUNCTION__")
$fileName Filename containing function (used with "__FILE__")
$line Line number of function call (used with "__LINE__")
Definition at line 145 of file htmlFunctions.php.
References PrintDebug().
Referenced by PrintHtmlFooter(), PrintHtmlHeader(), and PrintSieveTable().