Prime Number Solver: JavaScript Form Validation Functions
JavaScript Form Validation Functions
Functions
function IsInteger (intValue)
Determines if the passed value is an (signed) integer.
function IsUnsignedInteger (intValue)
Determines if the passed value is an unsigned (positive) integer.
function IsValidInteger (intValue, isUnsigned)
Determines if the passed value is an integer.
function ValidateMinValue (widgetName, minValue, defaultValue)
Displays an alert dialog if value is not greater than min.
Function Documentation
function IsInteger (intValue)
Determines if the passed value is an (signed) integer.
Author:
Fred R. McClurg
Date:
February 4, 2010
See also:
IsUnsignedInteger
Parameters:
intValue Value to be validated
Return values:
status Return TRUE if value is an integer
Definition at line 46 of file formValidation.js.
References IsValidInteger().
function IsUnsignedInteger (intValue)
Determines if the passed value is an unsigned (positive) integer.
Author:
Fred R. McClurg
Date:
February 4, 2010
See also:
IsInteger
Parameters:
intValue Value to be validated
Return values:
status Return TRUE if value is an integer
Definition at line 66 of file formValidation.js.
References IsValidInteger().
Referenced by ValidateMinValue().
function IsValidInteger (intValue, isUnsigned)
Determines if the passed value is an integer.
Author:
Fred R. McClurg
Date:
February 4, 2010
See also:
IsInteger
IsUnsignedInteger
Parameters:
intValue Value to be validated
isUnsigned If true, valid value is unsigned
Return values:
status Return TRUE if value is an integer
Definition at line 88 of file formValidation.js.
Referenced by IsInteger(), and IsUnsignedInteger().
function ValidateMinValue (widgetName, minValue, defaultValue)
Displays an alert dialog if value is not greater than min.
Author:
Fred R. McClurg
Date:
February 4, 2010
Parameters:
widgetName Name of the text control
minValue Minimum valid value
defaultValue Fallback value in case entered value is invalid
Definition at line 20 of file formValidation.js.
References IsUnsignedInteger().